version: '3.8'
services:
  opaochat:
    image: opaochat/subbygithub:latest
    restart: always
    container_name: subbygithub
    environment:
      - TZ=Asia/Shanghai
      # - EXECUTION_TIME_COLLECT="30 2 * * *"
      # - EXECUTION_TIME_PROCESS="30 2 * * *"
    volumes:
      - ./data:/aggregator/data
      - ./log:/log
      # - ./start.sh:/aggregator/start.sh

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 3600 opaochat
